# Generated by Django 4.0.1 on 2022-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_rating_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
