# Generated by Django 4.0.1 on 2022-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='photo_actor', to='photo.Actor', verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='genre',
            field=models.ManyToManyField(blank=True, to='photo.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='operator',
            field=models.ManyToManyField(blank=True, related_name='photo_operator', to='photo.Actor', verbose_name='Оператор'),
        ),
    ]
